version: "3"
services:
  mysql:
    container_name: searchengine-mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: search_engine
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: meriuts
      MYSQL_PASSWORD: secret
  redis:
    image: redis:7.0.12
    ports:
      - "6379:6379"

