server:
  port: 8888

spring:
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
#      maximum-pool-size: 100
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        generate_statistics: false
        order_inserts: true
        jdbc.batch_size: 10
    hibernate:
      ddl-auto: update
    show-sql: false

indexing-settings:
  sites:
#    - url: https://www.lenta.ru
#      name: Лента.ру
#    - url: https://www.skillbox.ru
#      name: Skillbox
#    - url: https://www.playback.ru
#      name: PlayBack.Ru
#    - url: https://opt-opt-opt.ru
#      name: Opt.Ru
    - url: https://example.q-parser.ru
      name: Q-Parser
    - url: https://obuv-tut2000.ru
      name: Obuv-tut2000
